click_registration_tab_xpath = "//a[normalize-space()='Register']"
first_name_xpath = "//input[@placeholder='First Name']"
last_name_xpath = "//input[@placeholder='Last Name']"
address_xpath = "//textarea[@ng-model='Adress']"
email_xpath = "//input[@type='email']"
phon_number_xpath = "//input[@type='tel']"
gender_xpath  = "//label[normalize-space()='Male']"
language_DD_xpath = "//div[@id='msdd']"
skill_DD_xpath = "//select[@id='Skills']"
country_DD_xpath = "//select[@id='countries']"
select_country_DD_xpath = "//span[@role='combobox']"
DOB_year_DD_xpath = "//select[@id='yearbox']"
DOB_month_DD_xpath = "//select[@placeholder='Month']"
DOB_date_DD_xpath = "//select[@id='daybox']"
password_xpath = "//input[@id='firstpassword']"
confirm_password_xpath = "//input[@id='secondpassword']"
submit_button_xpath = "//button[@id='submitbtn']"


